
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors:{
        whitesmoke: "#f7fafc",
        "theme-white-default": "#fff",
        "text-body-muted": "#718096",
        "gray-200": "#edf2f9",
        black: "#000",
        "theme-primary-soft": "#e1e8ff",
        "theme-primary-default": "#4c6fff",
        "text-body-light": "#425466",
        "theme-primary-dark": "#3754db",
        "input-muted-placeholder": "#7a828a",
        f2d3d: "#1f2d3d",
        "border-light": "#edf2f7",
        "theme-secondary-default": "#e4ecf7",
        "theme-dark-default": "#16192c",
        "table-head-background": "#fafafb",
        "table-head-text": "#8492a6", whitesmoke: "#f7fafc",
        "theme-white-default": "#fff",
        "theme-primary-default": "#4c6fff",
        mediumslateblue: "#3754db",
        "text-body-muted": "#718096",
        "input-muted-background": "#edf2f7",
        slategray: "#7a828a",
        "text-body-light": "#425466",
        "gray-200": "#edf2f9",
        whitesmoke: "#f7fafc",
        orangered: "#ff6000",
        black: "#000",
        "theme-primary-default": "#4c6fff",
        "text-body-muted": "#718096",
        "theme-white-default": "#fff",
        slateblue: "#6c5bd4",
        "text-heading-dark": "#27272e",
        "theme-secondary-dark": "#a6b7d4",
        "theme-tertiary-default": "#ff92ae",
        "theme-dark-default": "#16192c",
        "table-body-strong": "#425466",
        "theme-primary-dark": "#3754db",
        "input-muted-placeholder": "#7a828a",
        "gray-200": "#edf2f7",
        "theme-success-default": "#66cb9f",
        "theme-success-soft": "#deffee",
        "theme-warning-soft": "#ffede3",
        "theme-primary-soft": "#e1e8ff",
        "theme-tertiary-soft": "#ffeef1",
        gray1: "rgba(255, 255, 255, 0.44)",
        "theme-secondary-default": "#e4ecf7",
        "theme-dark-dark": "#101225",
      }, spacing: {},
      fontFamily: {
        "table-body-heading": "Inter",
      },
      borderRadius: {
        "81xl": "100px",
      },
      
    },fontSize: {
      sm: "14px",
      "3xs": "10px",
      xs: "12px",
      inherit: "inherit",
    },
  },
  plugins: [],
}